# **Student** **Performance Project**

In [1]:
import pandas as pd
import numpy as np

In [2]:
import plotly.express as px

In [5]:
import plotly.graph_objects as go

In [9]:
df = pd.read_excel('/content/student_performance_iris_style_300.xlsx')

In [10]:
df.head()

,student_id,study_hours,attendance_pct,assignments_completed,practice_score,sleep_hours,screen_time,performance_level
0,1,2.36,69.3,3,52.5,5.1,5.6,Low
1,2,3.49,64.0,4,50.4,10.6,5.9,Low
2,3,1.92,57.8,4,49.8,4.0,6.7,Low
3,4,1.82,59.4,4,43.7,10.4,6.5,Low
4,5,2.86,55.7,3,50.9,4.9,7.4,Low

In [11]:
df.describe()

,student_id,study_hours,attendance_pct,assignments_completed,practice_score,sleep_hours,screen_time
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,5.061500,78.083667,6.013333,68.213667,7.591000,4.323667
std,86.746758,2.064412,13.046473,2.972531,16.954767,1.732172,1.808270
min,1.000000,1.540000,55.200000,1.000000,40.200000,4.000000,1.500000
25%,75.750000,3.327500,65.500000,4.000000,51.350000,6.575000,2.675000
50%,150.500000,4.995000,79.400000,6.000000,68.350000,7.650000,4.200000
75%,225.250000,6.787500,90.550000,8.000000,84.825000,8.500000,5.925000
max,300.000000,8.790000,96.900000,11.000000,94.900000,11.000000,7.500000

In [14]:
df.shape

(300, 8)

In [15]:
df.set_index('student_id', inplace=True)
display(df.head())

,study_hours,attendance_pct,assignments_completed,practice_score,sleep_hours,screen_time,performance_level
student_id,,,,,,,
1,2.36,69.3,3,52.5,5.1,5.6,Low
2,3.49,64.0,4,50.4,10.6,5.9,Low
3,1.92,57.8,4,49.8,4.0,6.7,Low
4,1.82,59.4,4,43.7,10.4,6.5,Low
5,2.86,55.7,3,50.9,4.9,7.4,Low

In [16]:
df = df.reset_index()
display(df.head())

,student_id,study_hours,attendance_pct,assignments_completed,practice_score,sleep_hours,screen_time,performance_level
0,1,2.36,69.3,3,52.5,5.1,5.6,Low
1,2,3.49,64.0,4,50.4,10.6,5.9,Low
2,3,1.92,57.8,4,49.8,4.0,6.7,Low
3,4,1.82,59.4,4,43.7,10.4,6.5,Low
4,5,2.86,55.7,3,50.9,4.9,7.4,Low

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             300 non-null    int64
 1   study_hours            300 non-null    float64
 2   attendance_pct         300 non-null    float64
 3   assignments_completed  300 non-null    int64
 4   practice_score         300 non-null    float64
 5   sleep_hours            300 non-null    float64
 6   screen_time            300 non-null    float64
 7   performance_level      300 non-null    object
dtypes: float64(5), int64(2), object(1)
memory usage: 18.9+ KB

In [19]:
total_student=df.shape[0]
total_student

300

In [22]:
avg_study_hour=df['study_hours'].mean()
float(avg_study_hour)

5.0615

In [25]:
avg_attendance=df['attendance_pct'].mean()
float(avg_attendance)

78.08366666666666

In [26]:
avg_practice_score = df['practice_score'].mean()
float(avg_practice_score)

68.21366666666667

In [28]:
top_performance=df['performance_level'].value_counts().idxmax()

In [30]:
kpi_table = pd.DataFrame({
    'Total Students': [total_student],
    'Average Study Hours': [round(avg_study_hour,2)],
    'Average Attendance (%)': [round(avg_attendance,2)],
    'Average Practice Score': [round(avg_practice_score,2)],
    'Most Frequent Performance Level': [top_performance]
})

kpi_table

,Total Students,Average Study Hours,Average Attendance (%),Average Practice Score,Most Frequent Performance Level
0,300,5.06,78.08,68.21,Low

In [37]:
fig1= px.scatter(df, x='study_hours', y='practice_score',
                 color='performance_level',
                 title='Scatter Plot of Study Hours vs Practice Score')

fig1.show()

In [38]:
fig2= px.scatter(df, x='attendance_pct', y='practice_score',
                 color='performance_level',
                 color_discrete_sequence=px.colors.qualitative.Set2,
                 title='Scatter Plot of Attendance vs Practice Score')

fig2.show()

In [39]:
fig3 = px.box(df, x='performance_level', y='study_hours',
             title = 'Box Plot of Performance Level vs Study Hours')
fig3

In [45]:
fig4 =px.histogram(df, x='practice_score', color='performance_level',
                   barmode='overlay',
             title = 'Histogram of Performance Level vs Practice Score')
fig4.show()

In [42]:
corr=df.drop('student_id', axis = 'columns').corr(numeric_only= True)

In [43]:
corr

,study_hours,attendance_pct,assignments_completed,practice_score,sleep_hours,screen_time
study_hours,1.000000,0.899883,0.888982,0.906577,0.092792,-0.913540
attendance_pct,0.899883,1.000000,0.891245,0.920130,0.140126,-0.928968
assignments_completed,0.888982,0.891245,1.000000,0.898261,0.115903,-0.892624
practice_score,0.906577,0.920130,0.898261,1.000000,0.088285,-0.923301
sleep_hours,0.092792,0.140126,0.115903,0.088285,1.000000,-0.094525
screen_time,-0.913540,-0.928968,-0.892624,-0.923301,-0.094525,1.000000

In [44]:
fig5 = px.imshow(corr,text_auto= True,
                 title='Correlation Heatmap')
fig5.show()

# Conclusion

The main factor affecting the performance level of student are as follows


1.   Study Hours
2.   Practice Score
3.   Attendance